name: eopf-jupyterhub-dask
channels:
  - conda-forge
dependencies:
  - jupyterhub-singleuser
  - jupyterlab
  - jupyterlab-myst
  - jupyterlab-git
  - nbgitpuller
  - dask
  - dask-gateway
  - distributed
  - dask-labextension
