name: jupyterlab-default-latest
dependencies:
  - pip
  - conda
  - nomkl
  - cytoolz
  - lz4
  - ipywidgets
  - cachey
  - streamz
  - jupyterhub-singleuser
  - jupyterlab
  - dask-labextension>=5
  - nbclassic
  - dask
  - dask-gateway
  - xarray-eopf=0.2.5
  - netCDF4
  - zarr
  - fsspec
  - gdal
  - nbgitpuller
  - xarray=2024.11.0
  - folium
  - graphviz
  - mapclassify
  - matplotlib=3.10.0
  - matplotlib-inline=0.1.7
  - bottleneck=1.4.2
  - numpy=1.26.4
  - mystmd
  - cartopy
  - jupyterlab-myst
  - python-graphviz
  - geopandas
  - ipyleaflet
  - shapely
  - pystac-client
  - xcube-eopf=3.1.0
  - scikit-image
  - hvplot
  - datashader
  - nbgitpuller
  - pystac-client
  - jupyterlab-git
  - openeo>=0.44.0
  - xcube-stac
  - libgdal-jp2openjpeg
  
